"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ZipExportService = void 0;
const core_1 = require("@angular/core");
let ZipExportService = class ZipExportService {
    exportTemplates(files) {
        const zip = new JSZip();
        files.forEach(file => {
            zip.file(file.path, file.content);
        });
        const readme = this.generateReadme();
        zip.file('README.md', readme);
        zip.generateAsync({ type: 'blob' })
            .then((content) => {
            this.downloadBlob(content, 'compodoc-templates.zip');
        });
    }
    generateReadme() {
        return `# Compodoc Custom Templates

This ZIP file contains customized templates for Compodoc documentation generation.

## Contents

- **Templates** (\`.hbs\` files): Handlebars templates for generating documentation pages
- **Styles** (\`.css\` files): Stylesheets for customizing the appearance
- **Scripts** (\`.js\` files): JavaScript files for additional functionality

## Usage

1. Extract this ZIP file to a directory on your system
2. Use the \`--templates\` flag when running Compodoc to specify the path to your custom templates:

   \`\`\`bash
   compodoc -p tsconfig.json --templates ./path/to/custom/templates/
   \`\`\`

## Template Structure

- \`page.hbs\` - Main page template
- \`partials/\` - Directory containing partial templates
- \`styles/\` - Directory containing CSS files
- \`js/\` - Directory containing JavaScript files

## Customization Tips

1. **Templates**: Use Handlebars syntax to customize the HTML structure
2. **Styles**: Modify CSS to change colors, fonts, layout, etc.
3. **Scripts**: Add custom JavaScript functionality

## Backup

Always keep a backup of your original templates before making changes.

## Documentation

For more information about customizing Compodoc templates, visit:
https://compodoc.app/guides/template-customization.html

Generated by Compodoc Template Playground
`;
    }
    downloadBlob(blob, filename) {
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.style.display = 'none';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
    }
};
exports.ZipExportService = ZipExportService;
exports.ZipExportService = ZipExportService = __decorate([
    (0, core_1.Injectable)({
        providedIn: 'root'
    })
], ZipExportService);
//# sourceMappingURL=zip-export.service.js.map